title: NLP Notes
description: My Personal tech blog
author: Phani Teja
github: https://github.com/aphaniteja
about: This is my personal blog focused on NLP and ML
disqus_shortname: 
google_analytics:
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/aphaniteja"
    - icon: fa-linkedin
      link: "https://linkedin.com/in/phaniteja3"
    
    - icon: fa-github
      link: "https://github.com/aphaniteja"


urls:
    - text: About Me
      url: /about/
      #- text: My Projects
      #url: /projects/
      #- text: XML Feed
      #url: /feed.xml

url: "https://aphaniteja.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
